default: &default
  pool: 5
  timeout: 5000
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: person_identifer_development
  username: person_identifier
  password: person_identifier

